import type { HookResult } from "@nuxt/schema";
import type { AlertOptions } from "~/components/Alert.vue";
import type { Highlight } from "~/types/common";

declare module "#app" {
  interface RuntimeNuxtHooks {
    "custom:alert": (options: AlertOptions) => HookResult,
    "custom:goToHighlight": (highlight: Highlight) => HookResult,
    "custom:downloadNeeded": (groupId: string) => HookResult,
    "custom:markAutoEnhanced": (ids: number[]) => HookResult,
    "custom:markAutoGenerated": (ids: number[]) => HookResult,
    "custom:clearAutoImageEditors": (ids: number[]) => HookResult,
  }
  // interface NuxtHooks {
  // }
}
