/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["core_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["core_api_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segment/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Segment Pdf */
        post: operations["core_api_segment_pdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/process/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Pdf */
        post: operations["core_api_process_pdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gen-image-bytes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gen Image Bytes Endpoint */
        post: operations["core_api_gen_image_bytes_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance Text */
        post: operations["core_api_enhance_text"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spacy-ctx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spacy Context
         * @description Return a JSON object matching the SpaCyContext shape defined in the frontend types.
         */
        post: operations["core_api_spacy_context"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spacy-ctx/proto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spacy Context Proto
         * @description Binary protobuf endpoint. This is a new, separate endpoint from `/spacy-ctx`.
         *
         *     Requires generated Python protobuf bindings (`core.protos.spacy_pb2`).
         *     Generate them with protoc before enabling this endpoint.
         */
        post: operations["core_api_spacy_context_proto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ProcessPdfSegmentsOnlyResponse */
        ProcessPdfSegmentsOnlyResponse: {
            /** Segment Count */
            segment_count: number;
            /** Segments */
            segments: components["schemas"]["SegmentWithPos"][];
        };
        /** SegmentWithPos */
        SegmentWithPos: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Polygons */
            polygons: {
                [key: string]: [
                    number,
                    number
                ][];
            };
        };
        /**
         * Evaluator
         * @enum {string}
         */
        Evaluator: "minilm_catboost" | "nli_roberta" | "random";
        /** ProcessPdfBody */
        ProcessPdfBody: {
            model: components["schemas"]["Evaluator"];
        };
        /** ProcessPdfResponse */
        ProcessPdfResponse: {
            /** Ws Key */
            ws_key: string;
            /** Expires In */
            expires_in: number;
            /** Segment Count */
            segment_count: number;
            /** Segments */
            segments: components["schemas"]["SegmentWithPos"][];
        };
        /** BatchImageItem */
        BatchImageItem: {
            /** Ok */
            ok: boolean;
            /** Image B64 */
            image_b64?: string | null;
            /** Error */
            error?: string | null;
        };
        /** BatchTextsBody */
        BatchTextsBody: {
            /** Texts */
            texts: string[];
        };
        /** BatchEnhanceItem */
        BatchEnhanceItem: {
            /** Ok */
            ok: boolean;
            /** Text */
            text?: string | null;
            /** Error */
            error?: string | null;
        };
        /** NounChunk */
        NounChunk: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
        };
        /** SentToken */
        SentToken: {
            /** Text */
            text: string;
            /** Pos */
            pos_: string;
            /** Dep */
            dep_: string;
            /** Children */
            children: components["schemas"]["SentToken"][];
        };
        /** SpaCyContext */
        SpaCyContext: {
            /** Tokens */
            tokens: components["schemas"]["SpaCyToken"][];
            /** Sentences */
            sentences: components["schemas"]["SpacySent"][];
            /** Nounchunks */
            nounChunks: components["schemas"]["NounChunk"][];
        };
        /** SpaCyToken */
        SpaCyToken: {
            /** Text */
            text: string;
            /** Startbyte */
            startByte: number;
            /** Endbyte */
            endByte: number;
            /** Pos */
            pos: string;
            /** Finepos */
            finePos: string;
            /** Lemma */
            lemma: string;
            /** Deprel */
            deprel: string;
            /** Dephead */
            dephead: number;
            /** Morph */
            morph: {
                [key: string]: string;
            };
            /** Likenum */
            likeNum: boolean;
            /** Isstop */
            isStop: boolean;
            /** Sentenceid */
            sentenceId: number;
            /** Withinsentenceid */
            withinSentenceId: number;
        };
        /** SpacyContextResponse */
        SpacyContextResponse: {
            /** Contexts */
            contexts: components["schemas"]["SpaCyContext"][];
        };
        /** SpacySent */
        SpacySent: {
            root: components["schemas"]["SentToken"];
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** TextBody */
        TextBody: {
            /** Texts */
            texts: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_segment_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Pdf
                     * Format: binary
                     */
                    pdf: string;
                    /**
                     * Evaluator
                     * @enum {string}
                     */
                    model: "minilm_catboost" | "nli_roberta" | "random";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessPdfSegmentsOnlyResponse"];
                };
            };
        };
    };
    core_api_process_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Pdf
                     * Format: binary
                     */
                    pdf: string;
                    /**
                     * Evaluator
                     * @enum {string}
                     */
                    model: "minilm_catboost" | "nli_roberta" | "random";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessPdfResponse"];
                };
            };
        };
    };
    core_api_gen_image_bytes_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTextsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchImageItem"][];
                };
            };
        };
    };
    core_api_enhance_text: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTextsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchEnhanceItem"][];
                };
            };
        };
    };
    core_api_spacy_context: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpacyContextResponse"];
                };
            };
        };
    };
    core_api_spacy_context_proto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
