repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.3
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        exclude: .*api\/.*migrations\/.*
        args: [--fix]
      - id: ruff-format
        exclude: .*api\/.*migrations\/.*

  - repo: local
    hooks:
      - id: check-sync
        name: Check file sync
        entry: python3 modules/lab/src/check_sync.py
        language: system
        pass_filenames: false

  # - repo: local
  #   hooks:
  #     - id: eslint-deps
  #       name: "install eslint deps"
  #       language: script
  #       entry: modules/illustrator-app/utils/eslint_install_deps.sh
  #       require_serial: true

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.20.1
  #   hooks:
  #     - id: eslint
  #       files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
  #       types: [file]
  #       exclude: schema.d.ts
  #       additional_dependencies:
  #         - eslint@^9.10
  #       args: [--fix, --config, modules/illustrator-app/eslint.config.mjs]
