services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    entrypoint: []
    command: bash -c "python manage.py migrate && python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
      target: dev
