# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacy.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bspacy.proto\x12\x05spacy"\x99\x03\n\x05Token\x12\x14\n\x0cparagraph_id\x18\x01 \x01(\x05\x12\x13\n\x0bsentence_id\x18\x02 \x01(\x05\x12\x1a\n\x12within_sentence_id\x18\x03 \x01(\x05\x12\x10\n\x08token_id\x18\x04 \x01(\x05\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x0b\n\x03pos\x18\x06 \x01(\t\x12\x10\n\x08\x66ine_pos\x18\x07 \x01(\t\x12\r\n\x05lemma\x18\x08 \x01(\t\x12\x0e\n\x06\x64\x65prel\x18\t \x01(\t\x12\x0f\n\x07\x64\x65phead\x18\n \x01(\x05\x12\x0b\n\x03ner\x18\x0b \x01(\t\x12\x12\n\nstart_byte\x18\x0c \x01(\x05\x12\x10\n\x08\x65nd_byte\x18\r \x01(\x05\x12&\n\x05morph\x18\x0e \x03(\x0b\x32\x17.spacy.Token.MorphEntry\x12\x10\n\x08like_num\x18\x0f \x01(\x08\x12\x0f\n\x07is_stop\x18\x10 \x01(\x08\x12\r\n\x05itext\x18\x11 \x01(\t\x12\x10\n\x08in_quote\x18\x12 \x01(\x08\x12\r\n\x05\x65vent\x18\x13 \x01(\x08\x1a,\n\nMorphEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"Y\n\tSentToken\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04pos_\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65p_\x18\x03 \x01(\t\x12"\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\x10.spacy.SentToken"F\n\x08Sentence\x12\x1e\n\x04root\x18\x01 \x01(\x0b\x32\x10.spacy.SentToken\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05"5\n\tNounChunk\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t"w\n\x0cSpaCyContext\x12\x1c\n\x06tokens\x18\x01 \x03(\x0b\x32\x0c.spacy.Token\x12"\n\tsentences\x18\x02 \x03(\x0b\x32\x0f.spacy.Sentence\x12%\n\x0bnoun_chunks\x18\x03 \x03(\x0b\x32\x10.spacy.NounChunk"6\n\rSpaCyContexts\x12%\n\x08\x63ontexts\x18\x01 \x03(\x0b\x32\x13.spacy.SpaCyContextb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "spacy_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _TOKEN_MORPHENTRY._options = None
    _TOKEN_MORPHENTRY._serialized_options = b"8\001"
    _TOKEN._serialized_start = 23
    _TOKEN._serialized_end = 432
    _TOKEN_MORPHENTRY._serialized_start = 388
    _TOKEN_MORPHENTRY._serialized_end = 432
    _SENTTOKEN._serialized_start = 434
    _SENTTOKEN._serialized_end = 523
    _SENTENCE._serialized_start = 525
    _SENTENCE._serialized_end = 595
    _NOUNCHUNK._serialized_start = 597
    _NOUNCHUNK._serialized_end = 650
    _SPACYCONTEXT._serialized_start = 652
    _SPACYCONTEXT._serialized_end = 771
    _SPACYCONTEXTS._serialized_start = 773
    _SPACYCONTEXTS._serialized_end = 827
# @@protoc_insertion_point(module_scope)
